creation des entités
WildCodeSchool-2023-09/remfr-php-p3-afac974 pull request #1
Opened 2023-12-14 16:06 UTC by PALVAREZ67

2023-12-14 16:31 UTC, LauraW-code requested changes
Je pense que tu t'es loupé sur le nommage des entités, il faut rester en pascalCase, et je ne pense que tu es censé avoir des propriétés à rallonge avec des underscores, les données ne sont pas très compréhensibles. Il te suffit de reprendre la nom de l'entité qui est liée.

2023-12-14 16:31 UTC, LauraW-code commented on src/Entity/Artist.php
> +    private ?string $Description = null;
les propriétés ne devraient pas commencer par une majuscule, il faut utiliser le pascalCase pour le nommage

2023-12-14 16:31 UTC, LauraW-code commented on src/Entity/Artist.php
> +    private ?Users $Link_Users_Artist = null;
De même pas de majuscules et pas d'underscore, que du pascalCase pour les propriétés

2023-12-15 13:57 UTC, antoninbrdl24 requested changes
Je rejoins Laura , des changements requis , c'est limite plus facile de supprimer le commit et tout recommencer la je pense

2023-12-19 13:28 UTC, closed without merging

2023-12-19 13:28 UTC, PALVAREZ67 commented
je recommence