page contact , crud associé , fix de l'edit des roles pour les users…
WildCodeSchool-2023-09/remfr-php-p3-afac974 pull request #28
Opened 2024-01-15 16:03 UTC by antoninbrdl24

page contact , crud associé , fix de l'edit des roles pour les users , fix et ajout des csrf token pour les delete du dashboard admin

2024-01-15 16:10 UTC, PALVAREZ67 reviewed
dans ta modif de l'entity User, est ce que tu as regardé si en créant un nouveau compte le role_user se met bien par défaut ?

2024-01-22 09:09 UTC, PALVAREZ67 approved these changes

2024-01-23 08:39 UTC, vincentr-wcs requested changes

2024-01-23 08:39 UTC, vincentr-wcs commented on templates/admin/edit_user.html.twig
> +    {{ dump(form) }}
Faudrait enlever ce dump

2024-01-24 09:02 UTC, vincentr-wcs approved these changes

2024-01-24 09:02 UTC, merged