Accueil
WildCodeSchool-2023-09/remfr-php-p3-afac974 pull request #9
Opened 2023-12-21 11:26 UTC by antoninbrdl24

page d'accueil fini , changement de certaines variables de bootstrap , sémantique de la page faite

2023-12-21 14:47 UTC, LauraW-code requested changes

2023-12-21 14:47 UTC, LauraW-code commented on templates/include/_navbar.html.twig
> +    <img src="{{ asset('build/images/AFACv2.png') }}">
attention t'as laissé AFACv2.png et t'as rename le fichier en AFAC.png

2023-12-21 15:03 UTC, PALVAREZ67 approved these changes

2023-12-22 08:07 UTC, vincentr-wcs approved these changes

2023-12-22 08:07 UTC, merged